import type { Models } from 'appwrite';

// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types -l ts ./types`.

export enum UserType {
    USER = "user",
    AGENT = "agent",
    AGENCY = "agency"
}

export enum AccountStatus {
    ACTIVE = "active",
    INACTIVE = "inactive",
    SUSPENDED = "suspended",
    PENDING = "pending",
    BANNED = "banned"
}

export enum AvailabilityStatus {
    AVAILABLE = "available",
    BUSY = "busy",
    AWAY = "away",
    OFFLINE = "offline"
}

export enum Priority {
    LOW = "Low",
    MEDIUM = "Medium",
    HIGH = "High",
    URGENT = "Urgent"
}

export enum Status {
    PENDING = "Pending",
    SCHEDULED = "Scheduled",
    COMPLETED = "Completed",
    CANCELLED = "Cancelled",
    NO_ANSWER = "No Answer"
}

export enum Status {
    PENDING = "Pending",
    CONFIRMED = "Confirmed",
    COMPLETED = "Completed",
    CANCELLED = "Cancelled",
    RESCHEDULED = "Rescheduled"
}

export enum MeetingType {
    IN_PERSON = "In-Person",
    VIRTUAL = "Virtual",
    PHONE = "Phone"
}

export enum Source {
    WEBSITE_FORM = "Website Form",
    EMAIL = "Email",
    PHONE_CALL = "Phone Call",
    CHAT = "Chat",
    SOCIAL_MEDIA = "Social Media"
}

export enum Status {
    PENDING = "Pending",
    CONTACTED = "Contacted",
    COMPLETED = "Completed",
    CANCELLED = "Cancelled"
}

export enum Priority {
    LOW = "Low",
    MEDIUM = "Medium",
    HIGH = "High",
    URGENT = "Urgent"
}

export enum Status {
    HOT_LEAD = "Hot Lead",
    WARM_LEAD = "Warm Lead",
    COLD_LEAD = "Cold Lead",
    CONVERTED = "Converted",
    LOST = "Lost",
    UNQUALIFIED = "Unqualified"
}

export enum Source {
    WEBSITE = "Website",
    REFERRAL = "Referral",
    SOCIAL_MEDIA = "Social Media",
    EMAIL_CAMPAIGN = "Email Campaign",
    PHONE_CALL = "Phone Call",
    WALK_IN = "Walk-in",
    OTHER = "Other"
}

export enum FinancingStatus {
    PRE_APPROVED = "Pre-Approved",
    NEED_FINANCING = "Need Financing",
    CASH_BUYER = "Cash Buyer",
    NOT_SURE = "Not Sure"
}

export enum Timeline {
    IMMEDIATE = "Immediate",
    ONE_TO_THREE_MONTHS = "1-3 Months",
    THREE_TO_SIX_MONTHS = "3-6 Months",
    SIX_PLUS_MONTHS = "6+ Months",
    JUST_BROWSING = "Just Browsing"
}

export enum Status {
    ACTIVE = "active",
    PAUSED = "paused",
    SCHEDULED = "scheduled",
    EXPIRED = "expired",
    DRAFT = "draft"
}

export enum Status {
    DRAFT = "draft",
    SCHEDULED = "scheduled",
    SENDING = "sending",
    SENT = "sent",
    PAUSED = "paused",
    FAILED = "failed"
}

export enum Status {
    ACTIVE = "active",
    INACTIVE = "inactive",
    FULL = "full"
}

export enum Status {
    ACTIVE = "active",
    EXPIRED = "expired",
    PENDING = "pending",
    CANCELLED = "cancelled"
}

export enum DiscountType {
    PERCENTAGE = "percentage",
    FIXED = "fixed"
}

export enum Status {
    ACTIVE = "active",
    INACTIVE = "inactive",
    EXPIRED = "expired",
    SCHEDULED = "scheduled"
}

export enum Status {
    DRAFT = "draft",
    SCHEDULED = "scheduled",
    SENDING = "sending",
    SENT = "sent",
    FAILED = "failed"
}

export enum Type {
    CREDIT_CARD = "credit_card",
    DEBIT_CARD = "debit_card",
    PAYPAL = "paypal",
    BANK_TRANSFER = "bank_transfer",
    WALLET = "wallet",
    CRYPTO = "crypto",
    OTHER = "other"
}

export enum Status {
    TRIAL = "trial",
    ACTIVE = "active",
    PAST_DUE = "past_due",
    CANCELLED = "cancelled",
    EXPIRED = "expired",
    PAUSED = "paused"
}

export enum BillingCycle {
    MONTHLY = "monthly",
    QUARTERLY = "quarterly",
    YEARLY = "yearly",
    ONE_TIME = "one_time"
}

export enum Status {
    PENDING = "pending",
    ACTIVE = "active",
    EXPIRED = "expired",
    CANCELLED = "cancelled",
    PAUSED = "paused"
}

export enum Package {
    BASIC = "basic",
    STANDARD = "standard",
    PREMIUM = "premium",
    SPOTLIGHT = "spotlight"
}

export enum Priority {
    LOW = "low",
    MEDIUM = "medium",
    HIGH = "high",
    URGENT = "urgent"
}

export enum Status {
    PENDING = "pending",
    UNDER_REVIEW = "under_review",
    APPROVED = "approved",
    REJECTED = "rejected",
    PROCESSED = "processed",
    CANCELLED = "cancelled"
}

export enum Reason {
    SERVICE_NOT_AS_EXPECTED = "service_not_as_expected",
    TECHNICAL_ISSUES = "technical_issues",
    DUPLICATE_CHARGE = "duplicate_charge",
    CANCELLED_SUBSCRIPTION = "cancelled_subscription",
    CHANGED_MIND = "changed_mind",
    POOR_CUSTOMER_SERVICE = "poor_customer_service",
    BILLING_ERROR = "billing_error",
    OTHER = "other"
}

export enum Status {
    ACTIVE = "active",
    INACTIVE = "inactive",
    DEPRECATED = "deprecated",
    COMING_SOON = "coming_soon"
}

export enum BillingCycle {
    MONTHLY = "monthly",
    QUARTERLY = "quarterly",
    YEARLY = "yearly",
    ONE_TIME = "one_time"
}

export enum Status {
    DRAFT = "draft",
    PENDING = "pending",
    PAID = "paid",
    OVERDUE = "overdue",
    CANCELLED = "cancelled",
    REFUNDED = "refunded",
    PARTIALLY_PAID = "partially_paid"
}

export enum Type {
    SUBSCRIPTION = "subscription",
    FEATURED_LISTING = "featured_listing",
    REFUND = "refund",
    CREDIT = "credit",
    DEBIT = "debit",
    OTHER = "other"
}

export enum Status {
    PENDING = "pending",
    COMPLETED = "completed",
    FAILED = "failed",
    CANCELLED = "cancelled",
    PROCESSING = "processing"
}

export enum Category {
    BUYING_GUIDES = "buying_guides",
    SELLING_TIPS = "selling_tips",
    MARKET_ANALYSIS = "market_analysis",
    INVESTMENT = "investment",
    HOME_IMPROVEMENT = "home_improvement",
    NEIGHBORHOOD_GUIDES = "neighborhood_guides",
    REAL_ESTATE_NEWS = "real_estate_news",
    MORTGAGE_FINANCE = "mortgage_finance",
    LIFESTYLE = "lifestyle",
    OTHER = "other"
}

export enum Status {
    DRAFT = "draft",
    PENDING_REVIEW = "pending_review",
    SCHEDULED = "scheduled",
    PUBLISHED = "published",
    ARCHIVED = "archived"
}

export enum Status {
    DRAFT = "draft",
    PUBLISHED = "published",
    ARCHIVED = "archived"
}

export enum Category {
    GENERAL = "general",
    BUYING = "buying",
    SELLING = "selling",
    RENTING = "renting",
    PRICING = "pricing",
    AGENTS = "agents",
    LISTINGS = "listings",
    ACCOUNT = "account",
    PAYMENTS = "payments",
    SUPPORT = "support",
    LEGAL = "legal",
    OTHER = "other"
}

export enum Status {
    DRAFT = "draft",
    PUBLISHED = "published",
    ARCHIVED = "archived",
    MAINTENANCE = "maintenance"
}

export enum Template {
    DEFAULT = "default",
    FULL_WIDTH = "full_width",
    SIDEBAR_LEFT = "sidebar_left",
    SIDEBAR_RIGHT = "sidebar_right",
    LANDING = "landing",
    CONTACT = "contact",
    ABOUT = "about",
    LEGAL = "legal"
}

export enum TwitterCard {
    SUMMARY = "summary",
    SUMMARY_LARGE_IMAGE = "summary_large_image",
    APP = "app",
    PLAYER = "player"
}

export enum PageType {
    GLOBAL = "global",
    HOMEPAGE = "homepage",
    PROPERTIES = "properties",
    AGENTS = "agents",
    BLOG = "blog",
    CONTACT = "contact",
    ABOUT = "about",
    SEARCH = "search",
    CUSTOM = "custom"
}

export enum Status {
    PENDING = "pending",
    APPROVED = "approved",
    REJECTED = "rejected",
    FLAGGED = "flagged"
}

export enum AuthorRole {
    HOME_BUYER = "home_buyer",
    HOME_SELLER = "home_seller",
    RENTER = "renter",
    LANDLORD = "landlord",
    REAL_ESTATE_AGENT = "real_estate_agent",
    PROPERTY_INVESTOR = "property_investor",
    FIRST_TIME_BUYER = "first_time_buyer",
    OTHER = "other"
}

export enum Source {
    WEBSITE = "website",
    GOOGLE = "google",
    FACEBOOK = "facebook",
    YELP = "yelp",
    ZILLOW = "zillow",
    REALTOR = "realtor",
    MANUAL = "manual",
    OTHER = "other"
}

export enum Category {
    ACCOUNT = "account",
    PAYMENT = "payment",
    PROPERTY_LISTING = "property_listing",
    TECHNICAL = "technical",
    VERIFICATION = "verification",
    INQUIRY = "inquiry",
    COMPLAINT = "complaint",
    FEEDBACK = "feedback",
    OTHER = "other"
}

export enum RequesterRole {
    USER = "user",
    AGENT = "agent",
    AGENCY = "agency"
}

export enum Priority {
    LOW = "low",
    MEDIUM = "medium",
    HIGH = "high",
    URGENT = "urgent"
}

export enum Status {
    OPEN = "open",
    IN_PROGRESS = "in_progress",
    WAITING_CUSTOMER = "waiting_customer",
    ESCALATED = "escalated",
    RESOLVED = "resolved",
    CLOSED = "closed"
}

export enum Type {
    TEXT = "text",
    IMAGE = "image",
    FILE = "file",
    AUDIO = "audio",
    VIDEO = "video",
    PROPERTY_LINK = "property_link",
    LOCATION = "location",
    SYSTEM = "system"
}

export enum SenderRole {
    USER = "user",
    AGENT = "agent",
    AGENCY = "agency",
    STAFF = "staff",
    SUPPORT = "support",
    SYSTEM = "system"
}

export enum Status {
    SENDING = "sending",
    SENT = "sent",
    DELIVERED = "delivered",
    READ = "read",
    FAILED = "failed"
}

export enum InitiatorRole {
    USER = "user",
    AGENT = "agent",
    AGENCY = "agency",
    STAFF = "staff",
    SUPPORT = "support",
    SYSTEM = "system"
}

export enum Type {
    USER_TO_STAFF = "user_to_staff",
    AGENT_TO_STAFF = "agent_to_staff",
    AGENCY_TO_STAFF = "agency_to_staff",
    INTERNAL = "internal",
    SUPPORT_TICKET = "support_ticket"
}

export enum Status {
    ACTIVE = "active",
    PENDING = "pending",
    RESOLVED = "resolved",
    ARCHIVED = "archived",
    SPAM = "spam"
}

export type States = Models.Row & {
    country_id: string;
    name: string;
    state_code: string | null;
    is_active: boolean;
    timezone: string | null;
    area_sq_km: number | null;
    population: number | null;
    capital: string | null;
}

export type Countries = Models.Row & {
    name: string;
    iso_code: string;
    currency_code: string | null;
    cities: Cities[];
    is_active: boolean;
    population: number | null;
    flag_url: string | null;
    capital: string | null;
    continent: string | null;
    phone_code: string | null;
}

export type Locations = Models.Row & {
    city_id: string;
    name: string;
    area_type: string;
    longitude: number | null;
    latitude: number | null;
    city: Cities;
    total_area: number | null;
    established_year: number | null;
    developer_name: string | null;
    description: string | null;
    zone: string | null;
    district: string | null;
    postal_code: string | null;
    total_properties: number;
    is_active: boolean;
    is_gated: boolean;
    area_unit: string;
    properties: Properties[];
}

export type Cities = Models.Row & {
    state_id: string;
    name: string;
    city_code: string | null;
    longitude: number | null;
    latitude: number | null;
    country: Countries;
    areas_societies: Locations[];
    area_sq_km: number | null;
    is_active: boolean;
    postal_code_format: string | null;
    is_capital: boolean;
    timezone: string | null;
    population: number | null;
    country_id: string | null;
    properties: Properties[];
}

export type Amenities = Models.Row & {
    name: string;
    category: string;
    icon_name: string | null;
    is_premium: boolean;
    is_active: boolean;
    display_order: number;
    description: string | null;
    properties_count: number;
    is_searchable: boolean;
    is_featured: boolean;
    image_url: string | null;
    slug: string | null;
    meta_description: string | null;
    meta_title: string | null;
    properties: Properties[];
}

export type ListingTypes = Models.Row & {
    name: string;
    description: string | null;
    is_active: boolean;
    icon_name: string | null;
    properties: Properties[];
}

export type PropertyStatuses = Models.Row & {
    name: string;
    description: string | null;
    is_active: boolean;
    color_code: string | null;
    show_in_filter: boolean;
    is_default: boolean;
    display_order: number;
    icon_name: string | null;
    slug: string | null;
    badge_text: string | null;
    properties_count: number;
    properties: Properties[];
}

export type PropertyTypes = Models.Row & {
    name: string;
    category: string;
    description: string | null;
    icon_name: string | null;
    image_url: string | null;
    display_order: number;
    is_active: boolean;
    is_featured: boolean;
    properties_count: number;
    show_in_search: boolean;
    meta_description: string | null;
    meta_title: string | null;
    slug: string | null;
    properties: Properties[];
}

export type RealEstateCompanies = Models.Row & {
    name: string;
    license_number: string | null;
    email: string | null;
    phone: string | null;
    website: string | null;
    address: string | null;
    city_id: string | null;
    logo_url: string | null;
    is_verified: boolean;
    established_year: number | null;
    description: string | null;
    total_properties: number;
    total_reviews: number;
    rating: number;
    is_featured: boolean;
    is_active: boolean;
    active_listings: number;
    total_agents: number;
    social_media_linkedin: string | null;
    social_media_instagram: string | null;
    social_media_facebook: string | null;
}

export type Properties = Models.Row & {
    title: string;
    description: string | null;
    property_type_id: string;
    listing_type_id: string;
    property_status_id: string;
    location_id: string;
    address: string | null;
    bedrooms: number | null;
    bathrooms: number | null;
    kitchens: number;
    parking_spaces: number;
    area_unit: string;
    floors: number;
    floor_number: number | null;
    facing: string | null;
    currency: string;
    price_negotiable: boolean;
    condition_type: string;
    furnished_status: string;
    pet_policy: string;
    owner_id: string | null;
    agent_id: string | null;
    ownership_type: string;
    is_featured: boolean;
    is_verified: boolean;
    is_active: boolean;
    view_count: number;
    inquiry_count: number;
    favorite_count: number;
    main_image_url: string | null;
    virtual_tour_url: string | null;
    video_url: string | null;
    latitude: number | null;
    longitude: number | null;
    total_area: number | null;
    covered_area: number | null;
    price: number;
    maintenance_charges: number;
    has_basement: boolean;
    has_elevator: boolean;
    has_pool: boolean;
    has_garden: boolean;
    year_built: number | null;
    available_from: string | null;
    property_id_external: string | null;
    security_deposit: number | null;
    servant_quarters: number;
    energy_rating: string | null;
    lease_duration_months: number | null;
    balconies: number;
    building_name: string | null;
    unit_number: string | null;
    sector: string | null;
    block: string | null;
    street_address: string | null;
    plot_number: string | null;
    has_gym: boolean;
    has_powder_room: boolean;
    has_prayer_room: boolean;
    has_terrace: boolean;
    has_study_room: boolean;
    laundry_rooms: number;
    store_rooms: number;
    has_central_heating: boolean;
    has_central_ac: boolean;
    cooling_system: string | null;
    heating_system: string | null;
    flooring_type: string | null;
    electricity_backup: string | null;
    water_supply: string | null;
    is_mortgaged: boolean;
    land_registry_number: string | null;
    title_deed_number: string | null;
    possession_date: string | null;
    clear_title: boolean;
    construction_status: string | null;
    possession_status: string | null;
    seo_keywords: string | null;
    marketing_tagline: string | null;
    meta_description: string | null;
    youtube_video_id: string | null;
    video_tour_url: string | null;
    property_tax_annual: number | null;
    zoning_classification: string | null;
    is_urgent_sale: boolean;
    is_hot_deal: boolean;
    quality_score: number;
    total_images: number;
    featured_until: string | null;
    last_viewed_at: string | null;
    published_at: string | null;
    contact_person_name: string | null;
    contact_phone: string | null;
    contact_email: string | null;
    whatsapp_number: string | null;
    distance_to_city_center_km: number | null;
    distance_to_airport_km: number | null;
    nearby_mosques: string | null;
    nearby_transport: string | null;
    nearby_shopping: string | null;
    nearby_hospitals: string | null;
    nearby_schools: string | null;
    bank_loan_available: boolean;
    installment_available: boolean;
    installment_months: number | null;
    down_payment_percentage: number | null;
    service_charges_monthly: number | null;
    hoa_fees_monthly: number | null;
    utility_bills_average: number | null;
    is_west_open: boolean;
    is_corner: boolean;
    road_width_feet: number | null;
    corner_property: string | null;
    view_type: string | null;
    covered_parking: boolean;
    verification_status: string;
    availability: string;
    purpose: string;
    short_description: string | null;
    reference_id: string | null;
    slug: string | null;
    country_id: string | null;
    state_id: string | null;
    city_id: string | null;
    project_id: string | null;
    agency_id: string | null;
    price_range_id: string | null;
    furnishing_type_id: string | null;
    is_new_listing: boolean;
    is_exclusive: boolean;
    is_premium: boolean;
    is_published: boolean;
    meta_title: string | null;
    cover_image_url: string | null;
    cover_image_id: string | null;
    email_count: number;
    whatsapp_count: number;
    call_count: number;
    share_count: number;
    approved_by: string | null;
    updated_by: string | null;
    created_by: string | null;
    furnishing_type: FurnishingTypes;
    amenities: Amenities[];
    listing_type: ListingTypes;
    property_status: PropertyStatuses;
    property_type: PropertyTypes;
    price_range: PriceRanges;
    city: Cities;
    location: Locations;
}

export type PropertyFeatures = Models.Row & {
    property_id: string;
    amenity_id: string;
    notes: string | null;
    is_highlighted: boolean;
    display_order: number;
}

export type PropertyPriceHistory = Models.Row & {
    property_id: string;
    changed_by_user_id: string | null;
    change_reason: string;
    price_change_percentage: number | null;
    new_price: number;
    old_price: number | null;
    is_market_adjustment: boolean;
    currency: string;
}

export type PropertyImages = Models.Row & {
    property_id: string;
    image_url: string;
    image_title: string | null;
    image_type: string;
    display_order: number;
    is_main: boolean;
    file_size_kb: number | null;
    height: number | null;
    width: number | null;
    caption: string | null;
    thumbnail_url: string | null;
}

export type PropertyInquiries = Models.Row & {
    property_id: string;
    inquirer_id: string | null;
    inquirer_name: string | null;
    inquirer_email: string | null;
    inquirer_phone: string | null;
    subject: string | null;
    message: string;
    inquiry_type: string;
    preferred_contact_method: string;
    preferred_contact_time: string;
    status: string;
    agent_response: string | null;
    priority: number;
    is_read: boolean;
    source: string | null;
    responded_by_user_id: string | null;
    responded_at: string | null;
}

export type PropertyReviews = Models.Row & {
    property_id: string;
    reviewer_id: string;
    rating: number;
    review_text: string | null;
    review_type: string;
    is_verified_buyer: boolean;
    helpful_votes: number;
    is_approved: boolean;
    admin_response: string | null;
    approved_at: string | null;
    reviewer_name: string | null;
    pros: string | null;
    title: string;
    reviewer_email: string;
    is_active: boolean;
    response_date: string | null;
    response_text: string | null;
    helpful_count: number;
    is_published: boolean;
    is_verified: boolean;
    cons: string | null;
}

export type UserSavedProperties = Models.Row & {
    user_id: string;
    property_id: string;
    notes: string | null;
    is_favorite: boolean;
    priority: number;
    folder_name: string | null;
}

export type PropertyViews = Models.Row & {
    property_id: string;
    user_id: string | null;
    viewer_ip: string | null;
    user_agent: string | null;
    referrer: string | null;
    view_source: string;
    view_duration: number | null;
    country: string | null;
    browser: string | null;
    device_type: string | null;
    is_unique: boolean;
}

export type PropertyDocuments = Models.Row & {
    property_id: string;
    document_type: string;
    document_url: string;
    document_name: string | null;
    document_number: string | null;
    is_verified: boolean;
    uploaded_by_user_id: string | null;
    description: string | null;
    expiry_date: string | null;
    verified_at: string | null;
    file_size_kb: number | null;
    file_format: string | null;
}

export type PropertyTransactions = Models.Row & {
    property_id: string;
    transaction_type: string;
    buyer_id: string | null;
    seller_id: string | null;
    agent_id: string | null;
    currency: string;
    transaction_status: string;
    payment_method: string;
    legal_verification: boolean;
    document_verification: boolean;
    notes: string | null;
    commission_percentage: number | null;
    commission_amount: number | null;
    transaction_amount: number;
    payment_plan: string | null;
    completion_date: string | null;
    reference_number: string | null;
}

export type MortgageApplications = Models.Row & {
    user_id: string;
    property_id: string;
    bank_name: string | null;
    status: string;
    tenure_years: number | null;
    remarks: string | null;
    interest_rate: number | null;
    down_payment: number | null;
    loan_amount: number;
    application_number: string | null;
    monthly_income: number | null;
    employment_type: string | null;
}

export type PropertyReports = Models.Row & {
    property_id: string;
    reported_by_user_id: string | null;
    report_type: string;
    description: string;
    status: string;
    reviewed_by_admin_id: string | null;
    admin_notes: string | null;
    reviewed_at: string | null;
    reporter_email: string | null;
}

export type PropertyValuations = Models.Row & {
    property_id: string;
    valuation_type: string;
    valuation_by: string | null;
    agency_name: string | null;
    certification_number: string | null;
    remarks: string | null;
    is_verified: boolean;
    estimated_value: number;
    expiry_date: string | null;
    valuation_date: string | null;
    valuation_report_url: string | null;
}

export type PropertyAppointments = Models.Row & {
    property_id: string;
    user_id: string;
    agent_id: string | null;
    appointment_type: string;
    status: string;
    visitor_name: string | null;
    visitor_email: string | null;
    visitor_phone: string | null;
    notes: string | null;
    agent_notes: string | null;
    is_confirmed: boolean;
    duration_minutes: number;
    cancellation_reason: string | null;
    meeting_link: string | null;
}

export type MarketAnalytics = Models.Row & {
    location_id: string;
    property_type_id: string | null;
    total_listings: number;
    avg_days_on_market: number;
    total_sales: number;
    median_sale_price: number | null;
    avg_price_per_sqft: number | null;
}

export type NeighborhoodStats = Models.Row & {
    location_id: string;
    total_properties: number;
    schools_count: number;
    hospitals_count: number;
    restaurants_count: number;
    public_transport_distance: number;
    avg_property_price: number | null;
}

export type PropertyComparisons = Models.Row & {
    user_id: string;
    comparison_name: string | null;
    notes: string | null;
}

export type UserNotifications = Models.Row & {
    user_id: string;
    notification_type: string;
    title: string;
    message: string;
    related_property_id: string | null;
    related_user_id: string | null;
    is_read: boolean;
    action_url: string | null;
}

export type PropertyAlerts = Models.Row & {
    user_id: string;
    alert_name: string;
    location_id: string | null;
    property_type_id: string | null;
    min_bedrooms: number | null;
    max_bedrooms: number | null;
    frequency: string;
    is_active: boolean;
    matches_found: number;
    max_price: number | null;
    min_price: number | null;
}

export type ServiceRequests = Models.Row & {
    user_id: string | null;
    property_id: string | null;
    service_type: string;
    name: string;
    email: string;
    phone: string;
    description: string;
    status: string;
    priority: string;
    assigned_to_user_id: string | null;
    service_provider: string | null;
    notes: string | null;
}

export type FeedbackSubmissions = Models.Row & {
    user_id: string | null;
    name: string | null;
    email: string | null;
    feedback_type: string;
    subject: string | null;
    message: string;
    rating: number | null;
    page_url: string | null;
    status: string;
    is_anonymous: boolean;
    response: string | null;
}

export type ConsultationRequests = Models.Row & {
    user_id: string | null;
    name: string;
    email: string;
    phone: string;
    consultation_type: string;
    preferred_date: string | null;
    preferred_time: string | null;
    property_id: string | null;
    message: string | null;
    status: string;
    assigned_to_agent_id: string | null;
    meeting_link: string | null;
    notes: string | null;
}

export type NewsletterSubscriptions = Models.Row & {
    email: string;
    name: string | null;
    subscription_type: string;
    interests: string | null;
    is_active: boolean;
    is_verified: boolean;
    verification_token: string | null;
    unsubscribe_token: string | null;
    source: string | null;
    user_id: string | null;
}

export type CallbackRequests = Models.Row & {
    name: string;
    phone: string;
    email: string | null;
    preferred_time: string | null;
    callback_reason: string | null;
    property_id: string | null;
    status: string;
    assigned_to_agent_id: string | null;
    notes: string | null;
    is_completed: boolean;
}

export type ContactInquiries = Models.Row & {
    name: string;
    email: string;
    phone: string | null;
    subject: string;
    message: string;
    inquiry_type: string;
    status: string;
    priority: string;
    assigned_to_user_id: string | null;
    response_message: string | null;
    ip_address: string | null;
    user_agent: string | null;
    referrer_url: string | null;
}

export type Users = Models.Row & {
    username: string;
    total_sales: number;
    active_listings: number;
    total_listings: number;
    total_reviews: number;
    rating: number;
    is_active: boolean;
    is_premium: boolean;
    is_verified: boolean;
    experience_years: number;
    designation: string | null;
    company_id: string | null;
    license_number: string | null;
    profile_image_url: string | null;
    bio: string | null;
    company_name: string | null;
    last_name: string | null;
    first_name: string | null;
    phone: string | null;
    email: string;
    user_id: string;
    user_type: UserType;
    tax_id: string | null;
    response_time_hours: number;
    registration_number: string | null;
    commission_rate: number | null;
    preferred_contact_method: string | null;
    timezone: string | null;
    accepts_inquiries: boolean;
    is_featured: boolean;
    description: string | null;
    tagline: string | null;
    awards: string | null;
    certifications: string | null;
    team_size: number;
    established_year: number | null;
    service_areas: string | null;
    specializations: string | null;
    languages_spoken: string | null;
    office_hours: string | null;
    alternative_email: string | null;
    alternative_phone: string | null;
    whatsapp_number: string | null;
    social_media_youtube: string | null;
    social_media_instagram: string | null;
    social_media_twitter: string | null;
    social_media_facebook: string | null;
    social_media_linkedin: string | null;
    website_url: string | null;
    zip_code: string | null;
    country: string | null;
    state: string | null;
    city: string | null;
    address: string | null;
    banner_image_url: string | null;
    subscription_plan: string | null;
    account_status: AccountStatus;
    profile_completion_percentage: number;
    profile_views: number;
    total_inquiries_received: number;
    total_inquiries_sent: number;
    availability_status: AvailabilityStatus;
    response_rate_percentage: number;
    deals_closed: number;
    email_notifications_enabled: boolean;
    sms_notifications_enabled: boolean;
    push_notifications_enabled: boolean;
    marketing_emails_enabled: boolean;
    language_preference: string | null;
    currency_preference: string | null;
    broker_name: string | null;
    broker_license: string | null;
    rera_registration: string | null;
    insurance_info: string | null;
    property_types_handled: string | null;
    min_property_price: number | null;
    max_property_price: number | null;
    total_earnings: number;
    pending_commissions: number;
    credits_balance: number;
    identity_verified: boolean;
    documents_verified: boolean;
    background_check_completed: boolean;
    bank_account_verified: boolean;
    payment_method_verified: boolean;
    latitude: number | null;
    longitude: number | null;
}

export type CallRequests = Models.Row & {
    assigned_to: string | null;
    notes: string | null;
    scheduled_for: string | null;
    priority: Priority;
    status: Status;
    purpose: string;
    preferred_time: string | null;
    property_name: string | null;
    property_id: string | null;
    email: string | null;
    phone: string;
    name: string;
    language_preference: string | null;
    call_recording_url: string | null;
    completed_date: string | null;
    completed_by: string | null;
    follow_up_date: string | null;
    follow_up_required: boolean;
    call_outcome: string | null;
    call_duration_minutes: number | null;
    user_id: string | null;
}

export type ScheduleVisits = Models.Row & {
    assigned_agent: string | null;
    notes: string | null;
    status: Status;
    visit_time: string;
    visit_date: string;
    property_name: string | null;
    property_id: string;
    phone: string;
    email: string;
    name: string;
    agent_name: string | null;
    rescheduled_from: string | null;
    cancellation_reason: string | null;
    confirmation_sent: boolean;
    reminder_sent: boolean;
    meeting_type: MeetingType;
    location: string | null;
    duration_minutes: number;
    user_id: string | null;
}

export type ContactRequests = Models.Row & {
    assigned_to: string | null;
    admin_notes: string | null;
    source: Source | null;
    status: Status;
    message: string;
    subject: string;
    phone: string | null;
    email: string;
    name: string;
    user_id: string | null;
    follow_up_date: string | null;
    follow_up_required: boolean;
    is_spam: boolean;
    priority: Priority;
    response_date: string | null;
    responded_by: string | null;
    user_agent: string | null;
    ip_address: string | null;
}

export type Leads = Models.Row & {
    last_contact: string | null;
    activities: number;
    notes: string | null;
    assigned_to_name: string | null;
    assigned_to: string | null;
    score: number;
    status: Status;
    source: Source | null;
    property_name: string | null;
    property_id: string | null;
    phone: string | null;
    email: string;
    name: string;
    tags: string | null;
    lost_reason: string | null;
    conversion_date: string | null;
    next_follow_up_date: string | null;
    financing_status: FinancingStatus | null;
    timeline: Timeline | null;
    property_type_interest: string | null;
    preferred_location: string | null;
    budget_max: number | null;
    budget_min: number | null;
    company_name: string | null;
    user_id: string | null;
}

export type EmailTemplates = Models.Row & {
    last_used_at: string | null;
    usage_count: number;
    is_active: boolean;
    reply_to: string | null;
    from_email: string | null;
    from_name: string | null;
    description: string | null;
    variables: string | null;
    body_text: string | null;
    category: string;
    subject: string;
    name: string;
}

export type SmsTemplates = Models.Row & {
    character_count: number | null;
    last_used_at: string | null;
    usage_count: number;
    is_active: boolean;
    description: string | null;
    variables: string | null;
    category: string;
    content: string;
    name: string;
}

export type SystemNotifications = Models.Row & {
    is_active: boolean;
    recipients_count: number;
    action_url: string | null;
    icon: string | null;
    sent_at: string | null;
    scheduled_at: string | null;
    status: string;
    audience: string;
    type: string;
    message: string;
    title: string;
}

export type AgentReviews = Models.Row & {
    review_text: string;
    title: string;
    rating: number;
    agent_id: string;
    reviewer_id: string | null;
    reviewer_email: string;
    reviewer_name: string;
    is_active: boolean;
    response_date: string | null;
    response_text: string | null;
    helpful_count: number;
    is_published: boolean;
    is_verified: boolean;
    cons: string | null;
    pros: string | null;
}

export type ReportedReviews = Models.Row & {
    description: string;
    reason: string;
    reporter_email: string;
    reporter_name: string;
    property_id: string | null;
    agent_id: string | null;
    review_type: string;
    review_id: string;
    is_active: boolean;
    admin_notes: string | null;
    status: string;
}

export type BannerAds = Models.Row & {
    ctr: number;
    clicks: number;
    impressions: number;
    target_url: string | null;
    image_url: string | null;
    size: string;
    placement: string;
    name: string;
    status: Status;
    start_date: string | null;
    end_date: string | null;
    is_active: boolean;
}

export type EmailCampaigns = Models.Row & {
    sent_count: number;
    scheduled_date: string | null;
    sent_date: string | null;
    template_id: string | null;
    content: string | null;
    audience: string | null;
    subject: string;
    name: string;
    open_rate: number;
    click_rate: number;
    status: Status;
    is_automated: boolean;
    is_active: boolean;
}

export type FeaturedSlots = Models.Row & {
    is_active: boolean;
    status: Status;
    price: number;
    occupied: number;
    capacity: number;
    description: string | null;
    location: string;
    name: string;
}

export type FeaturedListings = Models.Row & {
    status: Status;
    expires: string | null;
    start_date: string | null;
    owner_name: string | null;
    owner_id: string | null;
    slot_id: string;
    property_name: string | null;
    property_id: string;
    is_active: boolean;
}

export type Promotions = Models.Row & {
    usage_count: number;
    end_date: string | null;
    start_date: string | null;
    discount_type: DiscountType;
    description: string | null;
    name: string;
    code: string;
    status: Status;
    usage_limit: number | null;
    discount_value: number;
    is_active: boolean;
}

export type PushNotifications = Models.Row & {
    open_rate: number;
    sent_count: number;
    sent_at: string | null;
    scheduled_for: string | null;
    action_url: string | null;
    target_audience: string | null;
    message: string;
    title: string;
    is_active: boolean;
    status: Status;
}

export type Images = Models.Row & {
    file_id: string;
    bucket_id: string;
    name: string;
    original_name: string | null;
    mime_type: string | null;
    file_size: number | null;
    width: number | null;
    height: number | null;
    url: string;
    thumbnail_url: string | null;
    medium_url: string | null;
    alt_text: string | null;
    title: string | null;
    caption: string | null;
    description: string | null;
    folder_id: string | null;
    uploaded_by: string | null;
    is_public: boolean;
    is_active: boolean;
    usage_count: number;
}

export type MediaFiles = Models.Row & {
    file_id: string;
    bucket_id: string;
    name: string;
    original_name: string | null;
    mime_type: string | null;
    file_extension: string | null;
    file_size: number | null;
    url: string;
    preview_url: string | null;
    description: string | null;
    folder_id: string | null;
    uploaded_by: string | null;
    file_type: string;
    is_public: boolean;
    is_active: boolean;
    download_count: number;
    last_accessed_at: string | null;
}

export type MediaFolders = Models.Row & {
    name: string;
    slug: string;
    parent_id: string | null;
    description: string | null;
    icon: string | null;
    color: string | null;
    display_order: number;
    path: string | null;
    files_count: number;
    total_size: number;
    created_by: string | null;
    is_public: boolean;
    is_active: boolean;
}

export type MediaTags = Models.Row & {
    name: string;
    slug: string;
    description: string | null;
    color: string | null;
    usage_count: number;
    created_by: string | null;
    is_active: boolean;
}

export type UserAvatars = Models.Row & {
    user_id: string;
    file_id: string;
    bucket_id: string;
    url: string;
    thumbnail_url: string | null;
    original_name: string | null;
    mime_type: string | null;
    file_size: number | null;
    width: number | null;
    height: number | null;
    is_active: boolean;
}

export type BannerImages = Models.Row & {
    name: string;
    file_id: string;
    bucket_id: string;
    url: string;
    mobile_url: string | null;
    link_url: string | null;
    link_target: string | null;
    title: string | null;
    subtitle: string | null;
    button_text: string | null;
    alt_text: string | null;
    placement: string;
    display_order: number;
    start_date: string | null;
    end_date: string | null;
    is_active: boolean;
    click_count: number;
    view_count: number;
    created_by: string | null;
}

export type Galleries = Models.Row & {
    name: string;
    slug: string;
    description: string | null;
    cover_image_url: string | null;
    cover_image_id: string | null;
    images_count: number;
    display_order: number;
    is_public: boolean;
    is_featured: boolean;
    is_active: boolean;
    created_by: string | null;
    gallery_type: string;
    related_entity_id: string | null;
    related_entity_type: string | null;
}

export type PaymentMethods = Models.Row & {
    is_active: boolean;
    is_verified: boolean;
    is_default: boolean;
    billing_address: string | null;
    holder_name: string | null;
    expiry_year: number | null;
    expiry_month: number | null;
    last_four: string | null;
    provider: string;
    type: Type;
    user_id: string;
}

export type UserSubscriptions = Models.Row & {
    is_active: boolean;
    is_auto_renew: boolean;
    last_payment_amount: number | null;
    last_payment_date: string | null;
    payment_method: string;
    cancellation_reason: string | null;
    cancelled_at: string | null;
    trial_end_date: string | null;
    next_billing_date: string | null;
    end_date: string;
    start_date: string;
    status: Status;
    billing_cycle: BillingCycle;
    currency: string;
    price: number;
    plan_name: string;
    plan_id: string;
    user_email: string;
    user_name: string;
    user_id: string;
}

export type FeaturedListingPayments = Models.Row & {
    is_active: boolean;
    is_auto_renew: boolean;
    position_priority: number;
    ctr: number;
    clicks: number;
    impressions: number;
    end_date: string;
    start_date: string;
    status: Status;
    transaction_id: string | null;
    payment_date: string;
    currency: string;
    amount: number;
    duration_days: number;
    package: Package;
    owner_name: string;
    owner_id: string;
    property_title: string;
    property_id: string;
}

export type RefundRequests = Models.Row & {
    is_active: boolean;
    admin_notes: string | null;
    processed_by_user_id: string | null;
    priority: Priority;
    rejection_reason: string | null;
    processed_date: string | null;
    status: Status;
    details: string;
    reason: Reason;
    request_date: string;
    currency: string;
    amount: number;
    service: string;
    invoice_id: string | null;
    transaction_id: string;
    customer_email: string;
    customer_name: string;
    customer_id: string;
    refund_id: string;
}

export type SubscriptionPlans = Models.Row & {
    is_active: boolean;
    has_api_access: boolean;
    has_priority_support: boolean;
    has_analytics: boolean;
    max_featured_listings: number;
    max_listings: number;
    trial_days: number;
    display_order: number;
    is_featured: boolean;
    is_popular: boolean;
    status: Status;
    total_revenue: number;
    subscribers_count: number;
    description: string | null;
    features: string;
    billing_cycle: BillingCycle;
    currency: string;
    price: number;
    slug: string;
    name: string;
}

export type Invoices = Models.Row & {
    is_active: boolean;
    billing_address: string | null;
    notes: string | null;
    payment_method: string | null;
    status: Status;
    paid_date: string | null;
    due_date: string;
    issue_date: string;
    currency: string;
    total: number;
    tax: number;
    amount: number;
    description: string;
    customer_email: string;
    customer_name: string;
    customer_id: string;
    invoice_number: string;
}

export type Transactions = Models.Row & {
    metadata: string | null;
    invoice_id: string | null;
    payment_method: string;
    amount: number;
    description: string;
    type: Type;
    user_name: string;
    user_id: string;
    transaction_id: string;
    is_active: boolean;
    status: Status;
    currency: string;
}

export type BlogPosts = Models.Row & {
    tags: string | null;
    author_avatar: string | null;
    author_name: string;
    author_id: string;
    featured_image: string | null;
    content: string;
    excerpt: string;
    slug: string;
    title: string;
    is_pinned: boolean;
    is_featured: boolean;
    reading_time: number;
    comments_count: number;
    likes_count: number;
    views_count: number;
    scheduled_at: string | null;
    published_at: string | null;
    category: Category;
    is_active: boolean;
    meta_keywords: string | null;
    meta_description: string | null;
    meta_title: string | null;
    status: Status;
}

export type FaQs = Models.Row & {
    is_active: boolean;
    status: Status;
    not_helpful_count: number;
    helpful_count: number;
    views_count: number;
    is_featured: boolean;
    display_order: number;
    category: Category;
    answer: string;
    question: string;
}

export type CmsPages = Models.Row & {
    published_at: string | null;
    status: Status;
    display_order: number;
    parent_id: string | null;
    template: Template;
    featured_image: string | null;
    excerpt: string | null;
    content: string;
    slug: string;
    title: string;
    is_active: boolean;
    custom_js: string | null;
    meta_keywords: string | null;
    meta_description: string | null;
    meta_title: string | null;
    show_in_footer: boolean;
    show_in_menu: boolean;
    views_count: number;
}

export type SeoSettings = Models.Row & {
    twitter_card: TwitterCard;
    og_type: string | null;
    og_image: string | null;
    og_description: string | null;
    og_title: string | null;
    meta_keywords: string | null;
    meta_description: string;
    site_title: string;
    page_type: PageType;
    setting_key: string;
    is_active: boolean;
    custom_head_tags: string | null;
    robots_directives: string | null;
    canonical_url: string | null;
    twitter_handle: string | null;
    twitter_image: string | null;
    twitter_description: string | null;
    twitter_title: string | null;
}

export type Testimonials = Models.Row & {
    display_order: number;
    is_featured: boolean;
    status: Status;
    rating: number;
    content: string;
    author_location: string | null;
    author_avatar: string | null;
    author_company: string | null;
    author_role: AuthorRole;
    author_name: string;
    is_active: boolean;
    approved_by: string | null;
    approved_at: string | null;
    submitted_at: string | null;
    agent_id: string | null;
    property_id: string | null;
    external_link: string | null;
    source: Source;
}

export type FurnishingTypes = Models.Row & {
    name: string;
    description: string | null;
    icon_name: string | null;
    display_order: number;
    is_active: boolean;
    slug: string | null;
    meta_description: string | null;
    meta_title: string | null;
    properties_count: number;
    is_default: boolean;
    image_url: string | null;
    properties: Properties[];
}

export type PriceRanges = Models.Row & {
    name: string;
    min_price: number;
    max_price: number | null;
    currency: string;
    listing_type: string;
    description: string | null;
    display_order: number;
    is_active: boolean;
    properties_count: number;
    is_default: boolean;
    property_type_id: string | null;
    label: string | null;
    slug: string | null;
    icon_name: string | null;
    properties: Properties[];
}

export type PropertyAmenities = Models.Row & {
    property_id: string;
    amenity_id: string;
    value: string | null;
    is_premium: boolean;
}

export type PropertyVideos = Models.Row & {
    property_id: string;
    video_id: string;
    display_order: number;
    is_main: boolean;
    is_active: boolean;
    title: string | null;
    description: string | null;
}

export type PropertyGalleries = Models.Row & {
    is_active: boolean;
    display_order: number;
    gallery_id: string;
    property_id: string;
}

export type MessageTemplates = Models.Row & {
    is_active: boolean;
    last_used_at: string | null;
    usage_count: number;
    variables: string | null;
    type: string;
    category: string;
    content: string;
    subject: string | null;
    slug: string;
    name: string;
    created_by_name: string;
    created_by_id: string;
}

export type SupportTickets = Models.Row & {
    category: Category;
    description: string;
    subject: string;
    requester_role: RequesterRole;
    requester_phone: string | null;
    requester_email: string;
    requester_name: string;
    requester_id: string;
    conversation_id: string;
    ticket_number: string;
    priority: Priority;
    resolution_notes: string | null;
    transaction_id: string | null;
    property_title: string | null;
    property_id: string | null;
    assigned_by_id: string | null;
    assigned_at: string | null;
    assigned_to_name: string | null;
    assigned_to_id: string | null;
    status: Status;
    escalation_reason: string | null;
    escalated_to_id: string | null;
    escalated_at: string | null;
    is_escalated: boolean;
    is_sla_breached: boolean;
    resolution_due_at: string | null;
    response_due_at: string | null;
    first_response_at: string | null;
    resolved_by_id: string | null;
    resolved_at: string | null;
    feedback_at: string | null;
    tags: string | null;
    attachments: string | null;
    closed_at: string | null;
    feedback_comment: string | null;
    reopened_at: string | null;
    satisfaction_rating: number | null;
}

export type Messages = Models.Row & {
    property_title: string | null;
    property_id: string | null;
    type: Type;
    sender_avatar_url: string | null;
    sender_role: SenderRole;
    sender_name: string;
    sender_id: string;
    conversation_id: string;
    is_internal_note: boolean;
    is_deleted: boolean;
    edited_at: string | null;
    is_edited: boolean;
    reply_to_preview: string | null;
    reply_to_id: string | null;
    read_by: string | null;
    status: Status;
    property_image_url: string | null;
    attachments: string | null;
    content: string;
}

export type Conversations = Models.Row & {
    initiator_role: InitiatorRole;
    type: Type;
    property_id: string | null;
    subject: string | null;
    assigned_at: string | null;
    assigned_to_name: string | null;
    assigned_to_id: string | null;
    initiator_name: string;
    initiator_id: string;
    participants: string | null;
    status: Status;
    reference_id: string;
    last_message_preview: string;
    property_title: string | null;
    last_message_at: string;
    last_message_by: string;
    total_messages: number;
    unread_count: number;
    unread_by_initiator: number;
    is_starred: boolean;
    is_muted: boolean;
    tags: string | null;
    archived_at: string | null;
    resolved_at: string | null;
    started_at: string;
}
