// Mock data for property search testing
// PropertyStatus enum values: active, pending, sold, rented, under_offer, off_market, draft, expired

export const PROPERTY_TYPES = [
  { id: "1", name: "House", slug: "house" },
  { id: "2", name: "Apartment", slug: "apartment" },
  { id: "3", name: "Villa", slug: "villa" },
  { id: "4", name: "Penthouse", slug: "penthouse" },
  { id: "5", name: "Studio", slug: "studio" },
  { id: "6", name: "Townhouse", slug: "townhouse" },
  { id: "7", name: "Duplex", slug: "duplex" },
  { id: "8", name: "Farmhouse", slug: "farmhouse" },
  { id: "9", name: "Commercial", slug: "commercial" },
  { id: "10", name: "Plot", slug: "plot" },
];

export const LISTING_TYPES = [
  { id: "1", name: "For Sale", slug: "sale" },
  { id: "2", name: "For Rent", slug: "rent" },
  { id: "3", name: "Lease", slug: "lease" },
];

export const PROPERTY_STATUSES = [
  { value: "active", name: "Active", color: "#22c55e" },
  { value: "pending", name: "Pending", color: "#f59e0b" },
  { value: "sold", name: "Sold", color: "#ef4444" },
  { value: "rented", name: "Rented", color: "#6366f1" },
  { value: "under_offer", name: "Under Offer", color: "#8b5cf6" },
  { value: "off_market", name: "Off Market", color: "#6b7280" },
  { value: "draft", name: "Draft", color: "#9ca3af" },
  { value: "expired", name: "Expired", color: "#dc2626" },
];

export const CITIES = [
  { id: "1", name: "Lahore" },
  { id: "2", name: "Karachi" },
  { id: "3", name: "Islamabad" },
  { id: "4", name: "Rawalpindi" },
  { id: "5", name: "Faisalabad" },
  { id: "6", name: "Multan" },
  { id: "7", name: "Peshawar" },
  { id: "8", name: "Quetta" },
];

export const FURNISHED_OPTIONS = [
  { value: "unfurnished", label: "Unfurnished" },
  { value: "semi-furnished", label: "Semi-Furnished" },
  { value: "fully-furnished", label: "Fully Furnished" },
];

export const CONDITION_TYPES = [
  { value: "new", label: "Brand New" },
  { value: "excellent", label: "Excellent" },
  { value: "good", label: "Good" },
  { value: "fair", label: "Fair" },
  { value: "needs-renovation", label: "Needs Renovation" },
];

export const AREA_UNITS = [
  { value: "sqft", label: "Sq. Ft" },
  { value: "sqm", label: "Sq. M" },
  { value: "marla", label: "Marla" },
  { value: "kanal", label: "Kanal" },
];

export const BEDROOM_OPTIONS = [
  { value: "1", label: "1" },
  { value: "2", label: "2" },
  { value: "3", label: "3" },
  { value: "4", label: "4" },
  { value: "5", label: "5" },
  { value: "6+", label: "6+" },
];

export const BATHROOM_OPTIONS = [
  { value: "1", label: "1" },
  { value: "2", label: "2" },
  { value: "3", label: "3" },
  { value: "4", label: "4" },
  { value: "5+", label: "5+" },
];

export const PRICE_RANGES = [
  { min: 0, max: 5000000, label: "Under 50 Lac" },
  { min: 5000000, max: 10000000, label: "50 Lac - 1 Crore" },
  { min: 10000000, max: 25000000, label: "1 - 2.5 Crore" },
  { min: 25000000, max: 50000000, label: "2.5 - 5 Crore" },
  { min: 50000000, max: 100000000, label: "5 - 10 Crore" },
  { min: 100000000, max: null, label: "10+ Crore" },
];

export const SORT_OPTIONS = [
  { value: "newest", label: "Newest First" },
  { value: "oldest", label: "Oldest First" },
  { value: "price-low", label: "Price: Low to High" },
  { value: "price-high", label: "Price: High to Low" },
  { value: "area-low", label: "Area: Low to High" },
  { value: "area-high", label: "Area: High to Low" },
  { value: "popular", label: "Most Popular" },
];

export interface MockProperty {
  id: string;
  title: string;
  slug: string;
  description: string;
  price: number;
  currency: string;
  property_type: string;
  listing_type: string;
  status: string;
  city: string;
  location: string;
  address: string;
  bedrooms: number;
  bathrooms: number;
  kitchens: number;
  parking_spaces: number;
  total_area: number;
  covered_area: number;
  area_unit: string;
  floors: number;
  floor_number: number | null;
  facing: string;
  furnished_status: string;
  condition_type: string;
  year_built: number | null;
  main_image_url: string;
  images: string[];
  is_featured: boolean;
  is_verified: boolean;
  is_hot_deal: boolean;
  is_new_listing: boolean;
  has_pool: boolean;
  has_garden: boolean;
  has_gym: boolean;
  has_elevator: boolean;
  has_basement: boolean;
  has_terrace: boolean;
  has_central_ac: boolean;
  has_central_heating: boolean;
  agent_name: string;
  agent_phone: string;
  view_count: number;
  created_at: string;
  published_at: string;
}

export const MOCK_PROPERTIES: MockProperty[] = [
  {
    id: "1",
    title: "Luxury 5-Bedroom Villa in DHA Phase 6",
    slug: "luxury-5-bedroom-villa-dha-phase-6",
    description: "Stunning luxury villa with modern architecture, spacious rooms, and premium finishes. Features a private pool, landscaped garden, and smart home automation.",
    price: 85000000,
    currency: "PKR",
    property_type: "Villa",
    listing_type: "For Sale",
    status: "Available",
    city: "Lahore",
    location: "DHA Phase 6",
    address: "123 Street 45, DHA Phase 6, Lahore",
    bedrooms: 5,
    bathrooms: 6,
    kitchens: 2,
    parking_spaces: 4,
    total_area: 1000,
    covered_area: 800,
    area_unit: "sqyd",
    floors: 3,
    floor_number: null,
    facing: "North",
    furnished_status: "fully-furnished",
    condition_type: "new",
    year_built: 2024,
    main_image_url: "/images/property-1.jpg",
    images: ["/images/property-1-1.jpg", "/images/property-1-2.jpg"],
    is_featured: true,
    is_verified: true,
    is_hot_deal: true,
    is_new_listing: true,
    has_pool: true,
    has_garden: true,
    has_gym: true,
    has_elevator: true,
    has_basement: true,
    has_terrace: true,
    has_central_ac: true,
    has_central_heating: true,
    agent_name: "Ahmad Khan",
    agent_phone: "+92 300 1234567",
    view_count: 1250,
    created_at: "2025-12-01T10:00:00Z",
    published_at: "2025-12-01T12:00:00Z",
  },
  {
    id: "2",
    title: "Modern 3-Bedroom Apartment in Gulberg",
    slug: "modern-3-bedroom-apartment-gulberg",
    description: "Contemporary apartment in the heart of Gulberg with stunning city views. Close to major shopping malls and restaurants.",
    price: 25000000,
    currency: "PKR",
    property_type: "Apartment",
    listing_type: "For Sale",
    status: "Available",
    city: "Lahore",
    location: "Gulberg III",
    address: "MM Alam Road, Gulberg III, Lahore",
    bedrooms: 3,
    bathrooms: 3,
    kitchens: 1,
    parking_spaces: 2,
    total_area: 2200,
    covered_area: 2000,
    area_unit: "sqft",
    floors: 12,
    floor_number: 8,
    facing: "East",
    furnished_status: "semi-furnished",
    condition_type: "excellent",
    year_built: 2022,
    main_image_url: "/images/property-2.jpg",
    images: ["/images/property-2-1.jpg", "/images/property-2-2.jpg"],
    is_featured: true,
    is_verified: true,
    is_hot_deal: false,
    is_new_listing: false,
    has_pool: false,
    has_garden: false,
    has_gym: true,
    has_elevator: true,
    has_basement: false,
    has_terrace: true,
    has_central_ac: true,
    has_central_heating: true,
    agent_name: "Sarah Ahmed",
    agent_phone: "+92 300 9876543",
    view_count: 890,
    created_at: "2025-11-15T10:00:00Z",
    published_at: "2025-11-15T12:00:00Z",
  },
  {
    id: "3",
    title: "Spacious 4-Bedroom House in Bahria Town",
    slug: "spacious-4-bedroom-house-bahria-town",
    description: "Well-maintained house in a family-friendly neighborhood. Features a beautiful lawn, modern kitchen, and ample parking space.",
    price: 45000000,
    currency: "PKR",
    property_type: "House",
    listing_type: "For Sale",
    status: "Available",
    city: "Lahore",
    location: "Bahria Town",
    address: "Block D, Bahria Town, Lahore",
    bedrooms: 4,
    bathrooms: 4,
    kitchens: 1,
    parking_spaces: 3,
    total_area: 10,
    covered_area: 8,
    area_unit: "marla",
    floors: 2,
    floor_number: null,
    facing: "West",
    furnished_status: "unfurnished",
    condition_type: "good",
    year_built: 2020,
    main_image_url: "/images/property-3.jpg",
    images: ["/images/property-3-1.jpg", "/images/property-3-2.jpg"],
    is_featured: false,
    is_verified: true,
    is_hot_deal: true,
    is_new_listing: false,
    has_pool: false,
    has_garden: true,
    has_gym: false,
    has_elevator: false,
    has_basement: false,
    has_terrace: false,
    has_central_ac: false,
    has_central_heating: false,
    agent_name: "Ali Hassan",
    agent_phone: "+92 321 5678901",
    view_count: 567,
    created_at: "2025-10-20T10:00:00Z",
    published_at: "2025-10-20T12:00:00Z",
  },
  {
    id: "4",
    title: "Premium Penthouse in Clifton",
    slug: "premium-penthouse-clifton",
    description: "Exclusive penthouse with panoramic sea views, private terrace, and luxury amenities. Perfect for those seeking the ultimate coastal lifestyle.",
    price: 150000000,
    currency: "PKR",
    property_type: "Penthouse",
    listing_type: "For Sale",
    status: "Available",
    city: "Karachi",
    location: "Clifton Block 9",
    address: "Sea View Apartments, Clifton Block 9, Karachi",
    bedrooms: 6,
    bathrooms: 7,
    kitchens: 2,
    parking_spaces: 4,
    total_area: 5500,
    covered_area: 4800,
    area_unit: "sqft",
    floors: 25,
    floor_number: 25,
    facing: "South",
    furnished_status: "fully-furnished",
    condition_type: "new",
    year_built: 2025,
    main_image_url: "/images/property-4.jpg",
    images: ["/images/property-4-1.jpg", "/images/property-4-2.jpg"],
    is_featured: true,
    is_verified: true,
    is_hot_deal: false,
    is_new_listing: true,
    has_pool: true,
    has_garden: false,
    has_gym: true,
    has_elevator: true,
    has_basement: false,
    has_terrace: true,
    has_central_ac: true,
    has_central_heating: false,
    agent_name: "Fatima Rizvi",
    agent_phone: "+92 333 4567890",
    view_count: 2340,
    created_at: "2025-12-10T10:00:00Z",
    published_at: "2025-12-10T12:00:00Z",
  },
  {
    id: "5",
    title: "Cozy Studio Apartment in F-11",
    slug: "cozy-studio-apartment-f11",
    description: "Perfect for young professionals or students. Modern studio with efficient layout, fully equipped kitchen, and great location near markets.",
    price: 85000,
    currency: "PKR",
    property_type: "Studio",
    listing_type: "For Rent",
    status: "Available",
    city: "Islamabad",
    location: "F-11 Markaz",
    address: "Silver Oaks Apartments, F-11, Islamabad",
    bedrooms: 1,
    bathrooms: 1,
    kitchens: 1,
    parking_spaces: 1,
    total_area: 650,
    covered_area: 600,
    area_unit: "sqft",
    floors: 6,
    floor_number: 4,
    facing: "North",
    furnished_status: "fully-furnished",
    condition_type: "excellent",
    year_built: 2021,
    main_image_url: "/images/property-5.jpg",
    images: ["/images/property-5-1.jpg", "/images/property-5-2.jpg"],
    is_featured: false,
    is_verified: true,
    is_hot_deal: false,
    is_new_listing: false,
    has_pool: false,
    has_garden: false,
    has_gym: true,
    has_elevator: true,
    has_basement: false,
    has_terrace: false,
    has_central_ac: true,
    has_central_heating: true,
    agent_name: "Omar Malik",
    agent_phone: "+92 345 6789012",
    view_count: 423,
    created_at: "2025-11-01T10:00:00Z",
    published_at: "2025-11-01T12:00:00Z",
  },
  {
    id: "6",
    title: "Elegant Townhouse in DHA Islamabad",
    slug: "elegant-townhouse-dha-islamabad",
    description: "Beautiful townhouse with modern design, private garden, and secure community. Ideal for families looking for a peaceful living environment.",
    price: 38000000,
    currency: "PKR",
    property_type: "Townhouse",
    listing_type: "For Sale",
    status: "Under Contract",
    city: "Islamabad",
    location: "DHA Phase 2",
    address: "Sector A, DHA Phase 2, Islamabad",
    bedrooms: 3,
    bathrooms: 4,
    kitchens: 1,
    parking_spaces: 2,
    total_area: 7,
    covered_area: 5,
    area_unit: "marla",
    floors: 2,
    floor_number: null,
    facing: "East",
    furnished_status: "unfurnished",
    condition_type: "new",
    year_built: 2024,
    main_image_url: "/images/property-6.jpg",
    images: ["/images/property-6-1.jpg", "/images/property-6-2.jpg"],
    is_featured: true,
    is_verified: true,
    is_hot_deal: false,
    is_new_listing: true,
    has_pool: false,
    has_garden: true,
    has_gym: false,
    has_elevator: false,
    has_basement: true,
    has_terrace: true,
    has_central_ac: false,
    has_central_heating: true,
    agent_name: "Zain Abbas",
    agent_phone: "+92 312 3456789",
    view_count: 756,
    created_at: "2025-12-05T10:00:00Z",
    published_at: "2025-12-05T12:00:00Z",
  },
  {
    id: "7",
    title: "Commercial Plaza in Blue Area",
    slug: "commercial-plaza-blue-area",
    description: "Prime commercial property in the heart of Blue Area. Ideal for corporate offices, banks, or retail outlets with high foot traffic.",
    price: 250000000,
    currency: "PKR",
    property_type: "Commercial",
    listing_type: "For Sale",
    status: "Available",
    city: "Islamabad",
    location: "Blue Area",
    address: "Jinnah Avenue, Blue Area, Islamabad",
    bedrooms: 0,
    bathrooms: 8,
    kitchens: 2,
    parking_spaces: 20,
    total_area: 15000,
    covered_area: 12000,
    area_unit: "sqft",
    floors: 8,
    floor_number: null,
    facing: "South",
    furnished_status: "unfurnished",
    condition_type: "good",
    year_built: 2018,
    main_image_url: "/images/property-7.jpg",
    images: ["/images/property-7-1.jpg", "/images/property-7-2.jpg"],
    is_featured: true,
    is_verified: true,
    is_hot_deal: true,
    is_new_listing: false,
    has_pool: false,
    has_garden: false,
    has_gym: false,
    has_elevator: true,
    has_basement: true,
    has_terrace: false,
    has_central_ac: true,
    has_central_heating: true,
    agent_name: "Bilal Ahmed",
    agent_phone: "+92 300 1112233",
    view_count: 1890,
    created_at: "2025-09-15T10:00:00Z",
    published_at: "2025-09-15T12:00:00Z",
  },
  {
    id: "8",
    title: "Farmhouse with Orchard in Bedian Road",
    slug: "farmhouse-orchard-bedian-road",
    description: "Peaceful farmhouse retreat with fruit orchard, swimming pool, and horse stable. Perfect weekend getaway or permanent countryside residence.",
    price: 120000000,
    currency: "PKR",
    property_type: "Farmhouse",
    listing_type: "For Sale",
    status: "Available",
    city: "Lahore",
    location: "Bedian Road",
    address: "Farmhouse Community, Bedian Road, Lahore",
    bedrooms: 6,
    bathrooms: 5,
    kitchens: 2,
    parking_spaces: 10,
    total_area: 4,
    covered_area: 2,
    area_unit: "kanal",
    floors: 1,
    floor_number: null,
    facing: "North",
    furnished_status: "semi-furnished",
    condition_type: "excellent",
    year_built: 2019,
    main_image_url: "/images/property-8.jpg",
    images: ["/images/property-8-1.jpg", "/images/property-8-2.jpg"],
    is_featured: true,
    is_verified: true,
    is_hot_deal: false,
    is_new_listing: false,
    has_pool: true,
    has_garden: true,
    has_gym: false,
    has_elevator: false,
    has_basement: false,
    has_terrace: true,
    has_central_ac: true,
    has_central_heating: true,
    agent_name: "Kamran Sheikh",
    agent_phone: "+92 321 9998877",
    view_count: 1456,
    created_at: "2025-08-20T10:00:00Z",
    published_at: "2025-08-20T12:00:00Z",
  },
  {
    id: "9",
    title: "2-Bedroom Apartment for Rent in E-11",
    slug: "2-bedroom-apartment-rent-e11",
    description: "Well-maintained apartment in a secure building. Features modern amenities, 24/7 security, and easy access to Margalla Hills hiking trails.",
    price: 120000,
    currency: "PKR",
    property_type: "Apartment",
    listing_type: "For Rent",
    status: "Available",
    city: "Islamabad",
    location: "E-11/4",
    address: "Margalla View Apartments, E-11/4, Islamabad",
    bedrooms: 2,
    bathrooms: 2,
    kitchens: 1,
    parking_spaces: 1,
    total_area: 1400,
    covered_area: 1300,
    area_unit: "sqft",
    floors: 10,
    floor_number: 6,
    facing: "North",
    furnished_status: "semi-furnished",
    condition_type: "excellent",
    year_built: 2020,
    main_image_url: "/images/property-9.jpg",
    images: ["/images/property-9-1.jpg", "/images/property-9-2.jpg"],
    is_featured: false,
    is_verified: true,
    is_hot_deal: false,
    is_new_listing: false,
    has_pool: false,
    has_garden: false,
    has_gym: true,
    has_elevator: true,
    has_basement: false,
    has_terrace: false,
    has_central_ac: true,
    has_central_heating: true,
    agent_name: "Nadia Khan",
    agent_phone: "+92 333 5566778",
    view_count: 345,
    created_at: "2025-11-25T10:00:00Z",
    published_at: "2025-11-25T12:00:00Z",
  },
  {
    id: "10",
    title: "Residential Plot in DHA Phase 5",
    slug: "residential-plot-dha-phase-5",
    description: "Prime residential plot in the most sought-after sector. Corner plot with extra land, ideal for building your dream home.",
    price: 35000000,
    currency: "PKR",
    property_type: "Plot",
    listing_type: "For Sale",
    status: "Available",
    city: "Lahore",
    location: "DHA Phase 5",
    address: "Block A, DHA Phase 5, Lahore",
    bedrooms: 0,
    bathrooms: 0,
    kitchens: 0,
    parking_spaces: 0,
    total_area: 1,
    covered_area: 0,
    area_unit: "kanal",
    floors: 0,
    floor_number: null,
    facing: "West",
    furnished_status: "unfurnished",
    condition_type: "new",
    year_built: null,
    main_image_url: "/images/property-10.jpg",
    images: ["/images/property-10-1.jpg", "/images/property-10-2.jpg"],
    is_featured: true,
    is_verified: true,
    is_hot_deal: true,
    is_new_listing: true,
    has_pool: false,
    has_garden: false,
    has_gym: false,
    has_elevator: false,
    has_basement: false,
    has_terrace: false,
    has_central_ac: false,
    has_central_heating: false,
    agent_name: "Usman Tariq",
    agent_phone: "+92 300 7778899",
    view_count: 890,
    created_at: "2025-12-12T10:00:00Z",
    published_at: "2025-12-12T12:00:00Z",
  },
  {
    id: "11",
    title: "Duplex House in Model Town",
    slug: "duplex-house-model-town",
    description: "Spacious duplex in the heart of Model Town. Two independent units perfect for extended family living or rental income potential.",
    price: 55000000,
    currency: "PKR",
    property_type: "Duplex",
    listing_type: "For Sale",
    status: "Available",
    city: "Lahore",
    location: "Model Town",
    address: "Block C, Model Town, Lahore",
    bedrooms: 6,
    bathrooms: 5,
    kitchens: 2,
    parking_spaces: 3,
    total_area: 12,
    covered_area: 10,
    area_unit: "marla",
    floors: 2,
    floor_number: null,
    facing: "East",
    furnished_status: "unfurnished",
    condition_type: "good",
    year_built: 2015,
    main_image_url: "/images/property-11.jpg",
    images: ["/images/property-11-1.jpg", "/images/property-11-2.jpg"],
    is_featured: false,
    is_verified: true,
    is_hot_deal: false,
    is_new_listing: false,
    has_pool: false,
    has_garden: true,
    has_gym: false,
    has_elevator: false,
    has_basement: true,
    has_terrace: true,
    has_central_ac: false,
    has_central_heating: false,
    agent_name: "Hammad Ali",
    agent_phone: "+92 345 1234567",
    view_count: 432,
    created_at: "2025-10-10T10:00:00Z",
    published_at: "2025-10-10T12:00:00Z",
  },
  {
    id: "12",
    title: "Luxury Apartment in Bahria Heights",
    slug: "luxury-apartment-bahria-heights",
    description: "Premium apartment in Bahria Heights with spectacular views. Features modern design, high-end finishes, and resort-style amenities.",
    price: 18000000,
    currency: "PKR",
    property_type: "Apartment",
    listing_type: "For Sale",
    status: "Coming Soon",
    city: "Karachi",
    location: "Bahria Town",
    address: "Bahria Heights, Bahria Town, Karachi",
    bedrooms: 2,
    bathrooms: 2,
    kitchens: 1,
    parking_spaces: 1,
    total_area: 1800,
    covered_area: 1650,
    area_unit: "sqft",
    floors: 20,
    floor_number: 15,
    facing: "South",
    furnished_status: "unfurnished",
    condition_type: "new",
    year_built: 2025,
    main_image_url: "/images/property-12.jpg",
    images: ["/images/property-12-1.jpg", "/images/property-12-2.jpg"],
    is_featured: true,
    is_verified: false,
    is_hot_deal: false,
    is_new_listing: true,
    has_pool: true,
    has_garden: true,
    has_gym: true,
    has_elevator: true,
    has_basement: false,
    has_terrace: false,
    has_central_ac: true,
    has_central_heating: false,
    agent_name: "Ayesha Siddiqui",
    agent_phone: "+92 312 8889999",
    view_count: 678,
    created_at: "2025-12-14T10:00:00Z",
    published_at: "2025-12-14T12:00:00Z",
  },
];

// Helper function to format price
export function formatPrice(price: number, currency: string = "PKR"): string {
  if (currency === "PKR") {
    if (price >= 10000000) {
      return `${(price / 10000000).toFixed(2)} Crore`;
    } else if (price >= 100000) {
      return `${(price / 100000).toFixed(2)} Lac`;
    }
  }
  return new Intl.NumberFormat("en-PK", {
    style: "currency",
    currency: currency,
    maximumFractionDigits: 0,
  }).format(price);
}

// Helper function to format area
export function formatArea(area: number, unit: string): string {
  return `${area.toLocaleString()} ${unit}`;
}
